# Generated by Django 3.1 on 2020-08-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200830_1159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='home_contact',
        ),
    ]
