# Generated by Django 3.1 on 2020-08-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='Uaddress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='confirm_password',
            new_name='Uconfirm_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='Udate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Uemail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Uname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Upassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='Uphone',
        ),
    ]
