# Generated by Django 3.1 on 2020-08-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200830_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AllUser',
        ),
    ]
