# Generated by Django 3.1 on 2020-08-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200830_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluser',
            old_name='Uaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='alluser',
            old_name='Uconfirm_password',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='alluser',
            old_name='Udate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='alluser',
            old_name='Uemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='alluser',
            old_name='Uname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='alluser',
            old_name='Upassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='alluser',
            old_name='Uphone',
            new_name='phone',
        ),
    ]
