# Generated by Django 3.1 on 2020-09-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200906_1340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registered',
            table='regUser',
        ),
    ]
