# Generated by Django 3.1 on 2020-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200906_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='registered',
            table='user',
        ),
    ]
