# Generated by Django 3.1 on 2020-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200906_2256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registered',
            table='register',
        ),
    ]
