# Generated by Django 3.1 on 2020-09-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20200906_2302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registered',
            table='register',
        ),
    ]
