# Generated by Django 3.1 on 2020-09-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20200906_2306'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registered',
            table='user',
        ),
    ]
